### ISSUE TITLE
Error in mingw make caflood.exe

### ISSUE THREAD

**Issue by JiaxuHuang** [FluiditLtd/caddies-caflood#1]
I tried using the Cmake and mingw to compilation binary exe. But it faild in the final step Linking CXX executable caflood.exe. Below is the error information. 
> CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x79): undefined reference to `__imp_send'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x561): undefined reference to `__imp_send'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x5ae): undefined reference to `__imp_closesocket'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0xa47): undefined reference to `__imp_recv'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x1227): undefined reference to `__imp_send'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x1bbf): undefined reference to `__imp_send'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3d3c): undefined reference to `__imp_WSAStartup'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3d56): undefined reference to `__imp_socket'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3d73): undefined reference to `__imp_htons'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3d85): undefined reference to `__imp_inet_addr'
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3da1): undefined reference to `__imp_connect' 
CMakeFiles\caflood.dir/objects.a(CouplingManager.cpp.obj):CouplingManager.cpp:(.text+0x3e18): undefined reference to `__imp_closesocket'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [apps\caddies-caflood\CMakeFiles\caflood.dir\build.make:320: apps/caddies-caflood/caflood.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:258: apps/caddies-caflood/CMakeFiles/caflood.dir/all] Error 2
mingw32-make: *** [Makefile:155: all] Error 2

**Comment by JiaxuHuang99** [comment]
When  I use VS2019 for compilation. The caflood.exe can be built. But It only works when the option is help. When the option is info, the output console is contrained to one line. If the length of the output information is over one line, it only shows one line.

> `C:\path\caflood3.exe /info D:\Caflood eat8a.csv d:\Caflood\out
> Copyright 2013鈥?021 University of Exeter & Fluidit Ltd.                                                               3
> App                  : caddies-caflood ver. 120

When the option is WCA2D, the output is 

> C:\path\caflood3.exe /WCA2D D:\Caflood\clarc eat8c96.csv d:\Caflood\out
 Pre-processing : EA Benchmarks Test 8a
> ken (s) = 0.0056
And the process stops. No more output and No increase in CPU usage and GPU usage.

**Comment by JiaxuHuang99** [comment]
I use VS2019 for compilation. The caflood.exe can be built. But It only works when the option is help. When the option is info, the output console is contrained to one line. If the length of the output information is over one line, it only shows one line

> C:\path\caflood3.exe /info D:\Caflood eat8a.csv d:\Caflood\out
> Copyright 2013鈥?021 University of Exeter & Fluidit Ltd. 3
> App : caddies-caflood ver. 120

When the option is WCA2D, the output is

> C:\path\caflood3.exe /WCA2D D:\Caflood\clarc eat8c96.csv d:\Caflood\out
> Pre-processing : EA Benchmarks Test 8a
> ken (s) = 0.0056

And the process stops. No more output and No increase in CPU usage and GPU usage

**Comment by JiaxuHuang99** [comment]
I use VS2019 for compilation. The caflood.exe can be built. But It only works when the option is help. When the option is info, the output console is contrained to one line. If the length of the output information is over one line, it only shows one line

> C:\path\caflood3.exe /info D:\Caflood eat8a.csv d:\Caflood\out
> Copyright 2013鈥?021 University of Exeter & Fluidit Ltd. 3
> App : caddies-caflood ver. 120

When the option is WCA2D, the output is


>  C:\path\caflood3.exe /info D:\Caflood eat8a.csv d:\Caflood\out
> Pre-processing : EA Benchmarks Test 8a
> ken (s) = 0.0056



And the process stops. No more output and No increase in CPU usage and GPU usage

**Comment by JiaxuHuang** [comment]
I use VS2019 for compilation. The caflood.exe can be built. But It only works when the option is help. When the option is info, the output console is contrained to one line. If the length of the output information is over one line, it only shows one line

> C:\path\caflood3.exe /info D:\Caflood eat8a.csv d:\Caflood\out
> Copyright 2013鈥?021 University of Exeter & Fluidit Ltd. 3
> App : caddies-caflood ver. 120

When the option is WCA2D, the output is

> C:\path\caflood3.exe /WCA2D D:\Caflood eat8a.csv d:\Caflood\out
> Pre-processing : EA Benchmarks Test 8a
> ken (s) = 0.0056

And the process stops. No more output and No increase in CPU usage and GPU usage

**Comment by JiaxuHuang** [comment]
After waiting for 10 minutes, the CPU usage increased to 10%, although I use the Nvidia OpenCL implementations. And I can find the output ASCII grid and point CSV. 
So how to run compiled caflood.exe on GPU? Compared with your published binary resource which fits Nvidia GPU well, it runs more slowly.
Another question is about the output console. There may be some problems with the encoding of the output strings on my PC.

**Comment by Umair-381** [comment]
Hello, I am also working on caflood. We can work together. I am waiting for your response. thanks

**Comment by makusuko** [comment]
When running CAFLOOD, one should follow the manual the original manual. In simplest case, one must supply options `--sim <source dir> <config.csv name> <output dir name>`.

To compile the GPU version, the OpenCL mode has to be enabled by supplying the implementation directory for the cmake command (as per caddies framework docs) e.g.:
`cmake -DCAAPI_OCL_EVENTS=disable -DCAAPI_SPECIFIC_IMPL_DIR=$(pwd)/impls/square-cell/vn-neighbours/1-levels/opencl -B build`

This requires you have the necessary OpenCL headers and ICD libraries available. We use Microsoft SDK on Windows (cmake -> nmake) and the Khronos OpenCL SDK. On Linux GCC is used. So it is quite possible to compile with GCC (e.g. Mingw, which I sometimes use on Linux to cross compile the Windows OpenMP build.

The compilation and user guides are available from University of Exeter: https://engineering.exeter.ac.uk/research/cws/resources/caddies/

**Comment by zyq91129** [comment]
CAFLOOD version 120 incorporates consideration for infiltration. However, I couldn't find relevant instructions or examples regarding the input file formats or how to input multiple water level events in the user manual. This has caused me considerable frustration. If you have a detailed user guide or examples of input files for the model, please send them to my email at zyq91129@gmail.com. Thank you!
